# Generated by Django 4.1.3 on 2022-11-16 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=20)),
                ('photo_url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=20)),
                ('photo_url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('runtime', models.PositiveIntegerField()),
                ('possible_age', models.CharField(choices=[('19', '19'), ('15', '15'), ('12', '12'), ('kids', 'Kids')], max_length=10)),
                ('episode', models.PositiveIntegerField(blank=True, null=True)),
                ('play_count', models.PositiveIntegerField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('actor', models.ManyToManyField(blank=True, to='videos.actor')),
                ('director', models.ManyToManyField(blank=True, to='videos.director')),
                ('genre', models.ForeignKey(default='', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.genre')),
                ('series', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.series')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
