# Generated by Django 4.1.3 on 2023-01-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_title', models.CharField(default='', max_length=100)),
                ('episode', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('runtime', models.PositiveIntegerField()),
                ('play_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('video_url', models.URLField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
