# Generated by Django 4.1.3 on 2022-11-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('genre', models.CharField(default='', max_length=20)),
                ('runtime', models.PositiveIntegerField()),
                ('possible_age', models.CharField(choices=[('19', '19'), ('15', '15'), ('12', '12'), ('kids', 'Kids')], max_length=10)),
                ('director', models.CharField(max_length=20)),
                ('actor', models.CharField(max_length=20)),
                ('episode', models.PositiveIntegerField()),
                ('play_count', models.PositiveIntegerField()),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
