# Generated by Django 4.1.3 on 2022-11-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='director',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
