databases:
  - name: watchaclone-db
    databaseName: watchaclone
    user: watchaclone
    region: singapore

services:
  - type: web
    name: watcha-clone-backend
    env: python
    plan: free
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: watchaclone-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
