# Generated by Django 4.1.3 on 2022-11-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('premium', 'Premium'), ('basic', 'Basic'), ('free', 'Free'), ('none', 'None')], max_length=15)),
                ('price', models.PositiveIntegerField()),
                ('HDR', models.BooleanField(default=False)),
                ('quality', models.BooleanField(default=False)),
                ('mobile', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
