# Generated by Django 4.1.3 on 2023-01-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='owner',
            new_name='user',
        ),
    ]
