# Generated by Django 4.1.3 on 2023-01-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_rename_user_coupon_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='username',
            new_name='user',
        ),
    ]
