# Generated by Django 4.1.3 on 2023-01-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_rename_username_coupon_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='user',
            new_name='name',
        ),
    ]
