# Generated by Django 4.1.3 on 2023-01-04 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_rename_user_coupon_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='name',
            new_name='user',
        ),
    ]
