# Generated by Django 4.1.3 on 2023-01-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_name', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, default='')),
                ('series', models.ManyToManyField(blank=True, to='series.series')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
