# Generated by Django 4.1.3 on 2023-01-04 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=20)),
                ('photo_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=20)),
                ('photo_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('possible_age', models.CharField(choices=[('all', 'All'), ('19', '19'), ('15', '15'), ('12', '12'), ('kids', 'Kids')], max_length=10)),
                ('summary', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, default='')),
                ('actor', models.ManyToManyField(blank=True, to='series.actor')),
                ('director', models.ManyToManyField(blank=True, to='series.director')),
                ('genre', models.ForeignKey(default='', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.genre')),
                ('video', models.ManyToManyField(blank=True, to='videos.video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
