# Generated by Django 4.1.3 on 2022-11-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=20)),
                ('possible_age', models.CharField(choices=[('19', '19'), ('15', '15'), ('12', '12'), ('kids', 'Kids')], max_length=10)),
                ('poster_url', models.URLField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
